### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by ghost** [knd/luatoml#1]
What are the libraries that are required to run this code?
I'm missing a 'util' library and a 'pl.pretty' library.

**Comment by ghost** [comment]
After viewing over the code, it seems there are no references to the libraries. Are they needed for something, or do the libraries declare global variables?

Also, on that note, try to make your libraries return a table (5.2's require() prefers this) or set a global table as to not clutter up _G with random functions.

**Comment by knd** [comment]
@AlissaSquared I'm not maintaining this library anymore. This was some minimal effort I put in back in college. I would feel honored if you fork and make it the way you see better. Cheers!
